version: '3'

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/kkodaira/42cursus/Inception/mine/docker/mariadb
            o: bind
            type: none

networks:
    mynet:
        name: mynet

services:
    mariadb:
        container_name: mariadb
        build: ./docker/mariadb/.
        image: mariadb:mine
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - mynet
        restart: always