version: '3'

volumes:
    data: {}
services:
    mariadb:
        build:
            dockerfile: docker/mariadb/Dockerfile
            context: .
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
    nginx:
        image: debian:buster
        # build:
        #     dockerfile: docker/nginx/Dockerfile
        #     context: .
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true
    wordpress:
        build:
            dockerfile: docker/wordpress/Dockerfile
            context: .
        restart: always
        volumes:
            - data:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge