version: '3'

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: ${PWD}/mariadb
            o: bind
            type: none
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: ${PWD}/wordpress
            o: bind
            type: none

networks:
    mynet:
        name: mynet

services:
    mariadb:
        container_name: mariadb
        build: ./docker/mariadb/
        image: mariadb:mine
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - mynet
        restart: always
    nginx:
        container_name: nginx
        build: ./docker/nginx/
        image: nginx:mine
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        networks:
            - mynet
        env_file:
            - .env
        restart: always
    wordpress:
        container_name: wordpress
        build: ./docker/wordpress/
        image: wordpress:mine
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        networks:
            - mynet
        restart: always